services:
  fut-medarbejder-web:
    image: kvalitetsit/fut-medarbejder-web:20b48200c9fb9817ec79187132527ffefde07a09
    ports:
      - 3000:80
    environment:
      # defaults to http://localhost:8080/v1/, but can point to other bff environments
      - REACT_APP_API_BASEURL=http://fut-medarbejder-bff:8080/v1/

  fut-medarbejder-bff:
    image: kvalitetsit/fut-medarbejder-bff:d5d1097fbac3a252ec65069a8437d205bfa07614
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      # defaults to devenvcgi, but can point to other eHealth environments
      - ehealth.environment=devenvcgi

      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
