package dk.kvalitetsit.fut.service;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.rest.client.api.IGenericClient;
import ca.uhn.fhir.rest.client.interceptor.BearerTokenAuthInterceptor;
import ca.uhn.fhir.rest.gclient.ReferenceClientParam;
import dk.kvalitetsit.fut.service.model.HelloServiceInput;
import org.hl7.fhir.r4.model.Bundle;
import org.hl7.fhir.r4.model.EpisodeOfCare;
import org.hl7.fhir.r4.model.Patient;
import org.junit.Before;
import org.junit.Test;

import java.util.UUID;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class HelloServiceImplTest {
    private HelloService helloService;

    @Before
    public void setup() {
        helloService = new HelloServiceImpl();
    }

    @Test
    public void testValidInput() {
        var input = new HelloServiceInput(UUID.randomUUID().toString());

        var result = helloService.helloServiceBusinessLogic(input);
        assertNotNull(result);
        assertNotNull(result.now());
        assertEquals(input.name(), result.name());
    }

    //@Test
    public void testme() {
        System.out.println("hello");
        FhirContext context = FhirContext.forR4();

//        IGenericClient client = context.newRestfulGenericClient("https://patient.devenvcgi.ehealth.sundhed.dk/fhir/Patient");

        // Create a context and get the client factory so it can be configured
        FhirContext ctx = FhirContext.forR4();
//        IRestfulClientFactory clientFactory = ctx.getRestfulClientFactory();

// In reality the token would have come from an authorization server
        String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJXMmxWUFYzWGpzTFFfWDhFRHdUV1pQLXU4UWFIMzNuUU11ZVB3algwcDN3In0.eyJleHAiOjE2NzgxMDg5MjgsImlhdCI6MTY3ODEwODYyOCwianRpIjoiNGFlYzZjMjEtMDZjOS00MGRmLTg5ZWUtMjdjMTU4NGMxMzhmIiwiaXNzIjoiaHR0cHM6Ly9zYW1sLmRldmVudmNnaS5laGVhbHRoLnN1bmRoZWQuZGsvYXV0aC9yZWFsbXMvZWhlYWx0aCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjZDNiMjk5NC04ZjVmLTQyMmQtYTY2NS01ZjY3MTI3YTljYTYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvaW9fbW9jayIsInNlc3Npb25fc3RhdGUiOiIxNmU2N2RjYS1kZjZhLTQ4OWUtOGE3Yi1hODlhNWFkMDMzMDYiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIlNTTFBhcnR5LnJlYWQiLCJPcmdhbml6YXRpb24ucmVhZCIsIkNvbW11bmljYXRpb24ucmVhZCIsIlRhc2suc2VhcmNoIiwiTWVkaWEuc2VhcmNoIiwiUXVlc3Rpb25uYWlyZVJlc3BvbnNlLnJlYWQiLCJQYXRpZW50LnJlYWQiLCJFcGlzb2RlT2ZDYXJlLmRlbGV0ZSIsIiRzZWFyY2gtbWVhc3VyZW1lbnRzIiwiQWN0aXZpdHlEZWZpbml0aW9uLnJlYWQiLCJBY3Rpb25HdWlkYW5jZS5yZWFkIiwiT3JnYW5pemF0aW9uLnNlYXJjaCIsIkNsaW5pY2FsIFZpZXdlciIsIkRldmljZU1ldHJpYy5yZWFkIiwiQ2l0aXplbiBFbnJvbGxlciIsInVtYV9hdXRob3JpemF0aW9uIiwiVGFzay5jcmVhdGUiLCJDb21tdW5pY2F0aW9uLnVwZGF0ZSIsIkNhcmVQbGFuJHVwZGF0ZS1jYXJlLXRlYW1zIiwiQ29uc2VudC5wYXRjaCIsIlRhc2sudXBkYXRlIiwiTGlicmFyeSRldmFsdWF0ZSIsIlByYWN0aXRpb25lci5zZWFyY2giLCJTU0xPcmRlckxpbmUuY3JlYXRlIiwiRGV2aWNlLnNlYXJjaCIsIlF1ZXN0aW9ubmFpcmUuc2VhcmNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLndyaXRlIiwiTGlicmFyeS5yZWFkIiwiUmVsYXRlZFBlcnNvbi5jcmVhdGUiLCJTU0xCbGFja0xpc3Qud3JpdGUiLCJTU0xPcmRlckxpbmUud3JpdGUiLCJEb2N1bWVudFJlZmVyZW5jZS5zZWFyY2giLCJNZWRpYS5yZWFkIiwiUHJvY2VkdXJlUmVxdWVzdC5yZWFkIiwiRXBpc29kZU9mQ2FyZS5yZWFkIiwiUGxhbkRlZmluaXRpb24uc2VhcmNoIiwiJHN1Ym1pdC1tZWFzdXJlbWVudCIsIlByb2NlZHVyZVJlcXVlc3QuY3JlYXRlIiwiUmVsYXRlZFBlcnNvbi5kZWxldGUiLCJEZXZpY2VNZXRyaWMuc2VhcmNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLnJlYWQiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG5vbmUiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG1lYXN1cmluZy1zdXBwb3J0IiwiRXBpc29kZU9mQ2FyZSRjcmVhdGUtZXBpc29kZS1vZi1jYXJlIiwiQ2FyZVBsYW4udXBkYXRlIiwiQ2xpbmljYWxJbXByZXNzaW9uLmRlbGV0ZSIsIkNvbnNlbnQucmVhZCIsIlNTTFBhY2thZ2UucmVhZCIsIkNvbW11bmljYXRpb24uZGVsZXRlIiwiQ29uc2VudC5jcmVhdGUiLCJUYXNrLmRlbGV0ZSIsIk9ic2VydmF0aW9uLnJlYWQiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG1lYXN1cmVtZW50LW1vbml0b3JpbmciLCJBY3Rpb25HaXVkYW5jZS5yZWFkIiwiUHJvY2VkdXJlUmVxdWVzdC5zZWFyY2giLCJTU0xPcmRlci5yZWFkIiwiUGxhbkRlZmluaXRpb24kYXBwbHkiLCJTU0xPcmRlci53cml0ZSIsIlNTTEFubm90YXRpb24ucmVhZCIsIk1vbml0b3JpbmcgQWRqdXN0ZXIiLCJDYXJlUGxhbi5yZWFkIiwiUXVlc3Rpb25uYWlyZVJlc3BvbnNlLnNlYXJjaCIsIlNTTFByb2JsZW0ucmVhZCIsIkNhcmVUZWFtLnNlYXJjaCIsIkFwcG9pbnRtZW50LnJlYWQiLCJDYXJlUGxhbi5zZWFyY2giLCJQbGFuRGVmaW5pdGlvbi5yZWFkIiwiU1NMQmxhY2tMaXN0LnJlYWQiLCJFcGlzb2RlT2ZDYXJlLnVwZGF0ZSIsIlByb2NlZHVyZVJlcXVlc3QudXBkYXRlIiwiQ29uc2VudC51cGRhdGUiLCJQZXJzb24kbWF0Y2giLCJQYXRpZW50JGNyZWF0ZVBhdGllbnRGcm9tUGVyc29uIiwiU1NMV2hpdGVMaXN0LnJlYWQiLCJQcm9jZWR1cmVSZXF1ZXN0LnBhdGNoIiwiT3JkZXIgUGxhY2VyIiwiQ29tbXVuaWNhdGlvblJlcXVlc3QudXBkYXRlIiwiU1NMVHJhY2VMaW5lLnJlYWQiLCJSZWxhdGVkUGVyc29uLndyaXRlIiwiJFNTTEZpbmRPckNyZWF0ZVBhcnR5IiwiQ29tbXVuaWNhdGlvbi5wYXRjaCIsIkNhcmVQbGFuLnBhdGNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLnVwZGF0ZSIsIkVwaXNvZGVPZkNhcmUud3JpdGUiLCJFcGlzb2RlT2ZDYXJlLnBhdGNoIiwiRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsIkNhcmVQbGFuLndyaXRlIiwiRGV2aWNlLnJlYWQiLCJDb25zZW50LnNlYXJjaCIsIk1vbml0b3JpbmcgQXNzaXN0b3IiLCJDb21tdW5pY2F0aW9uLmNyZWF0ZSIsIlRhc2sucmVhZCIsIkNvbW11bmljYXRpb24ud3JpdGUiLCJFcGlzb2RlT2ZDYXJlLmNyZWF0ZSIsIkNvbW11bmljYXRpb25SZXF1ZXN0LnJlYWQiLCJDYXJlUGxhbi5jcmVhdGUiLCJDb21tdW5pY2F0aW9uUmVxdWVzdC5jcmVhdGUiLCJDbGluaWNhbEltcHJlc3Npb24ucGF0Y2giLCJQcmFjdGl0aW9uZXIucmVhZCIsIkNhcmVQbGFuJHN1Z2dlc3QtY2FyZS10ZWFtcyIsIlByb2NlZHVyZVJlcXVlc3Qud3JpdGUiLCJQYXRpZW50LndyaXRlIiwiUXVlc3Rpb25uYWlyZS5yZWFkIiwiRGV2aWNlVXNlU3RhdGVtZW50LnJlYWQiLCJDbGluaWNhbEltcHJlc3Npb24uc2VhcmNoIiwiQWN0aXZpdHlEZWZpbml0aW9uLnNlYXJjaCIsIkVwaXNvZGVPZkNhcmUkaXMtY29udGV4dC1hbGxvd2VkIiwiU1NMQ2F0YWxvZ3VlSXRlbS5yZWFkIiwiQ2FyZVBsYW4uZGVsZXRlIiwiUGF0aWVudC5zZWFyY2giLCJDb25kaXRpb24uY3JlYXRlIiwiQ29uZGl0aW9uLnNlYXJjaCIsIm9mZmxpbmVfYWNjZXNzIiwiUmVsYXRlZFBlcnNvbi5wYXRjaCIsIkxpYnJhcnkuc2VhcmNoIiwiQXBwb2ludG1lbnQud3JpdGUiLCJSZWxhdGVkUGVyc29uLnVwZGF0ZSIsIlNTTFByb2JsZW0ud3JpdGUiLCJSZWxhdGVkUGVyc29uLnJlYWQiLCJDb25kaXRpb24ucmVhZCIsIlNTTE9yZGVyTGluZS5yZWFkIiwiRXBpc29kZU9mQ2FyZS5zZWFyY2giLCJWaWV3LnJlYWQiLCJDYXJlVGVhbS5yZWFkIiwiSW5jaWRlbnQgTWFuYWdlciIsIk9ic2VydmF0aW9uLnNlYXJjaCIsIkVwaXNvZGVPZkNhcmUkdXBkYXRlLWNhcmUtdGVhbXMiLCJkZWZhdWx0LXJvbGVzLWVoZWFsdGgiLCJTU0xDYXRhbG9ndWUucmVhZCIsIkNsaW5pY2FsSW1wcmVzc2lvbi5jcmVhdGUiLCJDYXJlUGxhbiR1cGRhdGUucmVzcG9uc2liaWxpdHkiLCJEZXZpY2VVc2VTdGF0ZW1lbnQuc2VhcmNoIiwiQ29tbXVuaWNhdGlvbi5zZWFyY2giLCJUYXNrLndyaXRlIiwiQ29tbXVuaWNhdGlvblJlcXVlc3Quc2VhcmNoIiwiU1NMT3JkZXIuY3JlYXRlIiwiUmVsYXRlZFBlcnNvbi5zZWFyY2giLCJQcm9jZWR1cmVSZXF1ZXN0LmRlbGV0ZSIsIlRhc2sucGF0Y2giXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiIxNmU2N2RjYS1kZjZhLTQ4OWUtOGE3Yi1hODlhNWFkMDMzMDYiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInVzZXJfdHlwZSI6IlBSQUNUSVRJT05FUiIsInVzZXJfaWQiOiJodHRwczovL29yZ2FuaXphdGlvbi5kZXZlbnZjZ2kuZWhlYWx0aC5zdW5kaGVkLmRrL2ZoaXIvUHJhY3RpdGlvbmVyLzEzNzEzOSIsIm5hbWUiOiJHcjZfbWVkYXJiZWpkZXI5IEpvaG5zb24iLCJjb250ZXh0Ijp7Im9yZ2FuaXphdGlvbl9pZCI6Imh0dHBzOi8vb3JnYW5pemF0aW9uLmRldmVudmNnaS5laGVhbHRoLnN1bmRoZWQuZGsvZmhpci9Pcmdhbml6YXRpb24vNDgwNjIiLCJjYXJlX3RlYW1faWQiOiJodHRwczovL29yZ2FuaXphdGlvbi5kZXZlbnZjZ2kuZWhlYWx0aC5zdW5kaGVkLmRrL2ZoaXIvQ2FyZVRlYW0vMTM1ODg0In0sInByZWZlcnJlZF91c2VybmFtZSI6ImdyNl9tZWRhcmJlamRlcjkiLCJnaXZlbl9uYW1lIjoiR3I2X21lZGFyYmVqZGVyOSIsImZhbWlseV9uYW1lIjoiSm9obnNvbiJ9.fSl2hRi3kxfADMxKjAOyenXZRwRMNjfpAUwi6WQDKcL0LuY3JEwbeBSCAOwZq8_i-qyIUzMOWBbQk0CoLJ89eEFGMqQbxSdPFvi5m8ypjhWLQ0z0F9RN-JgIO2rU3tSsKv-qkxT5D46hC3pTobdC4dNAUFUlj3dm2_VpaoQaWSn7x9j34rJBFT-796PTL99VILHmg9GdAWDNQ4XTO4PuMOHV_tOheqqFBqwcYo2j_P7yZ3a0n9rOMAadhu9bE-BG12u0l8OPyNxd0ER2-RHUV4Lp9mh2VJ1TAO5Nr3c49uDCDQXwR5L5B8E1bFt1ZSr9KddanozO8H9qo9rnunYcqQ";

        BearerTokenAuthInterceptor authInterceptor = new BearerTokenAuthInterceptor(token);

// Register the interceptor with your client (either style)
        IGenericClient client = ctx.newRestfulGenericClient("https://patient.devenvcgi.ehealth.sundhed.dk/fhir");
        client.registerInterceptor(authInterceptor);

        Bundle result = client
                .search()
                .forResource(Patient.class)
                .where(Patient.FAMILY.matches().value("Jørgensen"))
                .returnBundle(Bundle.class)
                .execute();
        result.getEntry().forEach(b -> System.out.println(b.getFullUrl()));
    }

    //@Test
    public void testme2() {
        FhirContext context = FhirContext.forR4();
        FhirContext ctx = FhirContext.forR4();

        String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJXMmxWUFYzWGpzTFFfWDhFRHdUV1pQLXU4UWFIMzNuUU11ZVB3algwcDN3In0.eyJleHAiOjE2Nzc4NDA1ODcsImlhdCI6MTY3Nzg0MDI4NywianRpIjoiN2ZiODE3ZjItMjRlMi00MmZiLWJkODQtZjdkN2M3ZGEwOGEwIiwiaXNzIjoiaHR0cHM6Ly9zYW1sLmRldmVudmNnaS5laGVhbHRoLnN1bmRoZWQuZGsvYXV0aC9yZWFsbXMvZWhlYWx0aCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjZDNiMjk5NC04ZjVmLTQyMmQtYTY2NS01ZjY3MTI3YTljYTYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvaW9fbW9jayIsInNlc3Npb25fc3RhdGUiOiIzODU2YTNkZS00OWU5LTQ4OGItYWI2Ni05MzY5YjUzODFhN2UiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIlNTTFBhcnR5LnJlYWQiLCJPcmdhbml6YXRpb24ucmVhZCIsIkNvbW11bmljYXRpb24ucmVhZCIsIlRhc2suc2VhcmNoIiwiTWVkaWEuc2VhcmNoIiwiUXVlc3Rpb25uYWlyZVJlc3BvbnNlLnJlYWQiLCJQYXRpZW50LnJlYWQiLCJFcGlzb2RlT2ZDYXJlLmRlbGV0ZSIsIiRzZWFyY2gtbWVhc3VyZW1lbnRzIiwiQWN0aXZpdHlEZWZpbml0aW9uLnJlYWQiLCJBY3Rpb25HdWlkYW5jZS5yZWFkIiwiT3JnYW5pemF0aW9uLnNlYXJjaCIsIkNsaW5pY2FsIFZpZXdlciIsIkRldmljZU1ldHJpYy5yZWFkIiwiQ2l0aXplbiBFbnJvbGxlciIsInVtYV9hdXRob3JpemF0aW9uIiwiVGFzay5jcmVhdGUiLCJDb21tdW5pY2F0aW9uLnVwZGF0ZSIsIkNhcmVQbGFuJHVwZGF0ZS1jYXJlLXRlYW1zIiwiQ29uc2VudC5wYXRjaCIsIlRhc2sudXBkYXRlIiwiTGlicmFyeSRldmFsdWF0ZSIsIlByYWN0aXRpb25lci5zZWFyY2giLCJTU0xPcmRlckxpbmUuY3JlYXRlIiwiRGV2aWNlLnNlYXJjaCIsIlF1ZXN0aW9ubmFpcmUuc2VhcmNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLndyaXRlIiwiTGlicmFyeS5yZWFkIiwiUmVsYXRlZFBlcnNvbi5jcmVhdGUiLCJTU0xCbGFja0xpc3Qud3JpdGUiLCJTU0xPcmRlckxpbmUud3JpdGUiLCJEb2N1bWVudFJlZmVyZW5jZS5zZWFyY2giLCJNZWRpYS5yZWFkIiwiUHJvY2VkdXJlUmVxdWVzdC5yZWFkIiwiRXBpc29kZU9mQ2FyZS5yZWFkIiwiUGxhbkRlZmluaXRpb24uc2VhcmNoIiwiJHN1Ym1pdC1tZWFzdXJlbWVudCIsIlByb2NlZHVyZVJlcXVlc3QuY3JlYXRlIiwiUmVsYXRlZFBlcnNvbi5kZWxldGUiLCJEZXZpY2VNZXRyaWMuc2VhcmNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLnJlYWQiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG5vbmUiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG1lYXN1cmluZy1zdXBwb3J0IiwiRXBpc29kZU9mQ2FyZSRjcmVhdGUtZXBpc29kZS1vZi1jYXJlIiwiQ2FyZVBsYW4udXBkYXRlIiwiQ2xpbmljYWxJbXByZXNzaW9uLmRlbGV0ZSIsIkNvbnNlbnQucmVhZCIsIlNTTFBhY2thZ2UucmVhZCIsIkNvbW11bmljYXRpb24uZGVsZXRlIiwiQ29uc2VudC5jcmVhdGUiLCJUYXNrLmRlbGV0ZSIsIk9ic2VydmF0aW9uLnJlYWQiLCJSZXN0cmljdGlvbkNhdGVnb3J5JG1lYXN1cmVtZW50LW1vbml0b3JpbmciLCJBY3Rpb25HaXVkYW5jZS5yZWFkIiwiUHJvY2VkdXJlUmVxdWVzdC5zZWFyY2giLCJTU0xPcmRlci5yZWFkIiwiUGxhbkRlZmluaXRpb24kYXBwbHkiLCJTU0xPcmRlci53cml0ZSIsIlNTTEFubm90YXRpb24ucmVhZCIsIk1vbml0b3JpbmcgQWRqdXN0ZXIiLCJDYXJlUGxhbi5yZWFkIiwiUXVlc3Rpb25uYWlyZVJlc3BvbnNlLnNlYXJjaCIsIlNTTFByb2JsZW0ucmVhZCIsIkNhcmVUZWFtLnNlYXJjaCIsIkFwcG9pbnRtZW50LnJlYWQiLCJDYXJlUGxhbi5zZWFyY2giLCJQbGFuRGVmaW5pdGlvbi5yZWFkIiwiU1NMQmxhY2tMaXN0LnJlYWQiLCJFcGlzb2RlT2ZDYXJlLnVwZGF0ZSIsIlByb2NlZHVyZVJlcXVlc3QudXBkYXRlIiwiQ29uc2VudC51cGRhdGUiLCJQZXJzb24kbWF0Y2giLCJQYXRpZW50JGNyZWF0ZVBhdGllbnRGcm9tUGVyc29uIiwiU1NMV2hpdGVMaXN0LnJlYWQiLCJQcm9jZWR1cmVSZXF1ZXN0LnBhdGNoIiwiT3JkZXIgUGxhY2VyIiwiQ29tbXVuaWNhdGlvblJlcXVlc3QudXBkYXRlIiwiU1NMVHJhY2VMaW5lLnJlYWQiLCJSZWxhdGVkUGVyc29uLndyaXRlIiwiJFNTTEZpbmRPckNyZWF0ZVBhcnR5IiwiQ29tbXVuaWNhdGlvbi5wYXRjaCIsIkNhcmVQbGFuLnBhdGNoIiwiQ2xpbmljYWxJbXByZXNzaW9uLnVwZGF0ZSIsIkVwaXNvZGVPZkNhcmUud3JpdGUiLCJFcGlzb2RlT2ZDYXJlLnBhdGNoIiwiRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsIkNhcmVQbGFuLndyaXRlIiwiRGV2aWNlLnJlYWQiLCJDb25zZW50LnNlYXJjaCIsIk1vbml0b3JpbmcgQXNzaXN0b3IiLCJDb21tdW5pY2F0aW9uLmNyZWF0ZSIsIlRhc2sucmVhZCIsIkNvbW11bmljYXRpb24ud3JpdGUiLCJFcGlzb2RlT2ZDYXJlLmNyZWF0ZSIsIkNvbW11bmljYXRpb25SZXF1ZXN0LnJlYWQiLCJDYXJlUGxhbi5jcmVhdGUiLCJDb21tdW5pY2F0aW9uUmVxdWVzdC5jcmVhdGUiLCJDbGluaWNhbEltcHJlc3Npb24ucGF0Y2giLCJQcmFjdGl0aW9uZXIucmVhZCIsIkNhcmVQbGFuJHN1Z2dlc3QtY2FyZS10ZWFtcyIsIlByb2NlZHVyZVJlcXVlc3Qud3JpdGUiLCJQYXRpZW50LndyaXRlIiwiUXVlc3Rpb25uYWlyZS5yZWFkIiwiRGV2aWNlVXNlU3RhdGVtZW50LnJlYWQiLCJDbGluaWNhbEltcHJlc3Npb24uc2VhcmNoIiwiQWN0aXZpdHlEZWZpbml0aW9uLnNlYXJjaCIsIkVwaXNvZGVPZkNhcmUkaXMtY29udGV4dC1hbGxvd2VkIiwiU1NMQ2F0YWxvZ3VlSXRlbS5yZWFkIiwiQ2FyZVBsYW4uZGVsZXRlIiwiUGF0aWVudC5zZWFyY2giLCJDb25kaXRpb24uY3JlYXRlIiwiQ29uZGl0aW9uLnNlYXJjaCIsIm9mZmxpbmVfYWNjZXNzIiwiUmVsYXRlZFBlcnNvbi5wYXRjaCIsIkxpYnJhcnkuc2VhcmNoIiwiQXBwb2ludG1lbnQud3JpdGUiLCJSZWxhdGVkUGVyc29uLnVwZGF0ZSIsIlNTTFByb2JsZW0ud3JpdGUiLCJSZWxhdGVkUGVyc29uLnJlYWQiLCJDb25kaXRpb24ucmVhZCIsIlNTTE9yZGVyTGluZS5yZWFkIiwiRXBpc29kZU9mQ2FyZS5zZWFyY2giLCJWaWV3LnJlYWQiLCJDYXJlVGVhbS5yZWFkIiwiSW5jaWRlbnQgTWFuYWdlciIsIk9ic2VydmF0aW9uLnNlYXJjaCIsIkVwaXNvZGVPZkNhcmUkdXBkYXRlLWNhcmUtdGVhbXMiLCJkZWZhdWx0LXJvbGVzLWVoZWFsdGgiLCJTU0xDYXRhbG9ndWUucmVhZCIsIkNsaW5pY2FsSW1wcmVzc2lvbi5jcmVhdGUiLCJDYXJlUGxhbiR1cGRhdGUucmVzcG9uc2liaWxpdHkiLCJEZXZpY2VVc2VTdGF0ZW1lbnQuc2VhcmNoIiwiQ29tbXVuaWNhdGlvbi5zZWFyY2giLCJUYXNrLndyaXRlIiwiQ29tbXVuaWNhdGlvblJlcXVlc3Quc2VhcmNoIiwiU1NMT3JkZXIuY3JlYXRlIiwiUmVsYXRlZFBlcnNvbi5zZWFyY2giLCJQcm9jZWR1cmVSZXF1ZXN0LmRlbGV0ZSIsIlRhc2sucGF0Y2giXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiIzODU2YTNkZS00OWU5LTQ4OGItYWI2Ni05MzY5YjUzODFhN2UiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInVzZXJfdHlwZSI6IlBSQUNUSVRJT05FUiIsInVzZXJfaWQiOiJodHRwczovL29yZ2FuaXphdGlvbi5kZXZlbnZjZ2kuZWhlYWx0aC5zdW5kaGVkLmRrL2ZoaXIvUHJhY3RpdGlvbmVyLzEzNzEzOSIsIm5hbWUiOiJHcjZfbWVkYXJiZWpkZXI5IEpvaG5zb24iLCJjb250ZXh0Ijp7Im9yZ2FuaXphdGlvbl9pZCI6Imh0dHBzOi8vb3JnYW5pemF0aW9uLmRldmVudmNnaS5laGVhbHRoLnN1bmRoZWQuZGsvZmhpci9Pcmdhbml6YXRpb24vNDgwNjIiLCJjYXJlX3RlYW1faWQiOiJodHRwczovL29yZ2FuaXphdGlvbi5kZXZlbnZjZ2kuZWhlYWx0aC5zdW5kaGVkLmRrL2ZoaXIvQ2FyZVRlYW0vMTM1ODg0In0sInByZWZlcnJlZF91c2VybmFtZSI6ImdyNl9tZWRhcmJlamRlcjkiLCJnaXZlbl9uYW1lIjoiR3I2X21lZGFyYmVqZGVyOSIsImZhbWlseV9uYW1lIjoiSm9obnNvbiJ9.bFKSaZYFo5EM8dE8keR_OtmrAZSelMhQqxAGCmQs1QoPlYF9gjhLkaRZu4P8fOHk05V4EBNiPHx4VXVd1wWWCrYGlrEe_EmxAnRj8puz6AlNj7M9SD55AIhVJ7Fq5IrVAwM59p3LXIQ6gcz8Co7QWLlukhAKfX30h2mOpypI1JIB18Wcyz23R6JQcN_s4kNNByHE-MD1nkarLqgsWrvv-fwGsKMjg7Xmccks4Bhs4o7USai2kakIaNM5Au_aepskfvIn6iwCdq4JFr52dT-Z-7BotCdihbN9wf4mbygE44L0g6PnglTvON5gzHWDXZtWdL7UXLUWJA8lwpz_bwQizg";
        BearerTokenAuthInterceptor authInterceptor = new BearerTokenAuthInterceptor(token);

// Register the interceptor with your client (either style)
        IGenericClient client = ctx.newRestfulGenericClient("https://careplan.devenvcgi.ehealth.sundhed.dk/fhir");
        client.registerInterceptor(authInterceptor);

        Bundle result = client
                .search()
                .forResource(EpisodeOfCare.class)
                .where(new ReferenceClientParam("team").hasAnyOfIds("https://organization.devenvcgi.ehealth.sundhed.dk/fhir/CareTeam/135884"))
                .returnBundle(Bundle.class)
                .execute();

        result.getEntry().forEach(b -> System.out.println(b.getFullUrl()));
    }
}
